ALTER SESSION SET current_schema = G212IF685_EQ07;

DROP TABLE tb_compra FORCE;
DROP TABLE tb_cliente_pf FORCE;
DROP TABLE tb_cliente_pj FORCE;
DROP TABLE tb_cliente FORCE;
DROP TABLE tb_entrega FORCE;
DROP TABLE tb_endereco FORCE;
DROP TABLE tb_pedido FORCE;
DROP TABLE tb_pagamento FORCE; 
DROP TABLE tb_produto FORCE; 


/* CHECKLIST
13. CREATE TABLE OF ✅
14. WITH ROWID REFERENCES ✅
16. SCOPE IS ✅
*/


CREATE TABLE tb_endereco OF tp_endereco (
	CEP NOT NULL,
    LOGRADOURO NOT NULL,
	BAIRRO NOT NULL,
	CIDADE NOT NULL,
	ESTADO NOT NULL,
    NUMERO NOT NULL,
	APARTAMENTO NOT NULL,   
	CONSTRAINT ENDERECO_PK PRIMARY KEY (CEP, NUMERO, APARTAMENTO)
);

CREATE TABLE tb_cliente OF tp_cliente (
    TELEFONE NOT NULL,
    ENDERECO WITH ROWID REFERENCES tb_endereco
);

CREATE TABLE tb_cliente_pf OF tp_cliente_pf (
	CPF PRIMARY KEY,
    NOME NOT NULL,
	DATA_NASCIMENTO NOT NULL,
	SEXO NOT NULL, 
    ENDERECO SCOPE IS tb_endereco
);

CREATE TABLE tb_cliente_pj OF tp_cliente_pj (
    CNPJ PRIMARY KEY,
	RAZAO_SOCIAL NOT NULL,
	NOME_FANTASIA NOT NULL,
	STATUS_CNPJ NOT NULL,
	CAPITAL_SOCIAL NOT NULL,
	PORTE NOT NULL
	);
	
CREATE TABLE tb_pedido OF tp_pedido (
    ID_PEDIDO PRIMARY KEY,
    STATUS NOT NULL
) NESTED TABLE detalhe_pedido STORE AS nt_detalhe_pedido;


CREATE TABLE tb_entrega OF tp_entrega(
    ID_ENTREGA PRIMARY KEY,
    STATUS_ENTREGA NOT NULL,
    DATA_POSTAGEM NULL,
    DATA_ENTREGA NULL,
    ENDERECO WITH ROWID REFERENCES tb_endereco
);


CREATE TABLE tb_pagamento OF tp_pagamento (
    ID_PAGAMENTO PRIMARY KEY,
    STATUS_PAGAMENTO NOT NULL,
    DATA_PAGAMENTO NULL
);

CREATE TABLE tb_produto OF tp_produto (
    SKU PRIMARY KEY,
	NOME NOT NULL,
	DESCRICAO NOT NULL,
	PRECO NOT NULL
);

CREATE TABLE tb_compra OF tp_compra (
    CLIENTE_PF   WITH ROWID REFERENCES tb_cliente_pf,
    CLIENTE_PJ WITH ROWID REFERENCES tb_cliente_pj,
    PEDIDO    WITH ROWID REFERENCES tb_pedido,
    PAGAMENTO WITH ROWID REFERENCES tb_pagamento,
    DATA_COMPRA NOT NULL,
    VALOR_COMPRA NOT NULL
);
